trigger:
- master

pool:
  name: linux 
steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'app/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'Cobertura'
    javaHomeOption: 'Path'
    jdkDirectory: '$JAVA_HOME'
    mavenVersionOption: 'Path'
    mavenDirectory: '$M2_HOME/bin'
    mavenSetM2Home: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false